### PR TITLE
Fix light theme

### PR DESCRIPTION
**Pull request by Zeromax**
The current Problem is, that the App is useless if you Switch to the light theme. The Background and Text was colored wrong.

I started to fix it.

The only Problem I see at the Moment is the Header wich has this gradiant. Therfore the Clock and the "loading" hint is not really good readable.

### CODE REVIEW

**Comment by Zeromax** [comment]
example for the clock Problem:

wp_ss_20150429_0003

Any sugestions? Remove the gradiant would be the easiest, or add a White line for the Background...

**Comment by NPadrutt** [comment]
If you remove the gradient, wouldn't the clock disappear completly?

**Comment by Zeromax** [comment]
Nope, cause the gradiant is part of the Header and I mean remove the Color as well to have it black or White in the Background.

But for me this is part of the App and I would like to have the gradiant as well in the light theme

**Comment by NPadrutt** [comment]
you could change the color of the items in the system try.

Maybe this helps: http://stackoverflow.com/questions/28527348/windows-phone-8-app-how-to-change-color-of-clock-and-top-bar-icons

**Comment by Zeromax** [comment]
Oh cool. So I will make it White ;)

**Comment by NPadrutt** [comment]
:)

**Comment by Zeromax** [comment]
WTF! It was not possible to set it to `White`. I have to use `#FFFFFE` Which is nearly White. It costs a complete hour to figure this out... To late in the evening maybe ;)

**Comment by Zeromax** [comment]
I think it looks fine now.

wp_ss_20150429_0004

**Comment by NPadrutt** [comment]
Looks nice! gj.

I can merge your pull request. Though if you want to have an update you will have to ask @michelsalib   to do so.

**Comment by Zeromax** [comment]
Ok Thank you.

**Pull request merged**
